# Generated by Django 6.0.5 on 2026-05-27 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conceptoingreso',
            name='requiere_jugador',
            field=models.BooleanField(default=False, help_text='Mostrar campo jugador en POS cuando se seleccione este concepto', verbose_name='Requiere jugador'),
        ),
    ]
