# Generated by Django 6.0.5 on 2026-05-27 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_conceptoingreso_requiere_jugador'),
    ]

    operations = [
        migrations.AddField(
            model_name='conceptoingreso',
            name='requiere_equipo',
            field=models.BooleanField(default=False, help_text='Obligar a seleccionar un equipo en POS', verbose_name='Requiere equipo'),
        ),
    ]
