# Generated by Django 6.0.5 on 2026-05-28 02:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_conceptoingreso_requiere_equipo'),
        ('league', '0016_temporada_es_prueba'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingreso',
            name='temporada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingresos', to='league.temporada'),
        ),
    ]
