# Generated by Django 6.0.5 on 2026-06-01 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_ingreso_temporada'),
    ]

    operations = [
        migrations.AddField(
            model_name='conceptoingreso',
            name='no_eliminar',
            field=models.BooleanField(default=False, help_text='Protegido contra eliminación desde el listado', verbose_name='No eliminar'),
        ),
    ]
