# Generated by Django 6.0.5 on 2026-06-01 16:38

from django.db import migrations


def crear_concepto_multa(apps, schema_editor):
    ConceptoIngreso = apps.get_model('finance', 'ConceptoIngreso')
    ConceptoIngreso.objects.get_or_create(
        nombre='Multa por incumplimiento de edad',
        defaults={
            'descripcion': 'Multa aplicada automáticamente cuando se modifica la fecha de nacimiento de un jugador y queda fuera del rango de edad de su categoría.',
            'monto_defecto': 500.00,
            'activo': True,
            'no_eliminar': True,
            'requiere_jugador': True,
            'requiere_equipo': True,
        }
    )


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_conceptoingreso_no_eliminar'),
    ]

    operations = [
        migrations.RunPython(crear_concepto_multa),
    ]
