# Generated by Django 6.0.5 on 2026-06-02 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_crear_concepto_multa_edad'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conceptoingreso',
            options={'verbose_name': 'Concepto', 'verbose_name_plural': 'Conceptos'},
        ),
        migrations.AlterModelOptions(
            name='ingreso',
            options={'verbose_name': 'Movimiento', 'verbose_name_plural': 'Movimientos'},
        ),
        migrations.AddField(
            model_name='conceptoingreso',
            name='tipo',
            field=models.CharField(choices=[('INGRESO', 'Ingreso'), ('EGRESO', 'Egreso')], default='INGRESO', max_length=10, verbose_name='Tipo'),
        ),
        migrations.AddField(
            model_name='ingreso',
            name='pagado_a',
            field=models.CharField(blank=True, help_text='Nombre del proveedor o persona a quien se pagó (solo egresos)', max_length=200, verbose_name='Pagado a'),
        ),
    ]
