# Generated by Django 6.0.5 on 2026-06-02 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_alter_conceptoingreso_options_alter_ingreso_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingreso',
            options={'ordering': ['-fecha_registro'], 'verbose_name': 'Movimiento', 'verbose_name_plural': 'Movimientos'},
        ),
        migrations.AddField(
            model_name='ingreso',
            name='cantidad',
            field=models.PositiveIntegerField(default=1, help_text='Número de unidades (ej: 3 arbitrajes)', verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total'),
        ),
    ]
