# Generated by Django 6.0.5 on 2026-06-04 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_alter_ingreso_options_ingreso_cantidad_and_more'),
        ('league', '0044_arbitro_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='conceptoingreso',
            name='categoria',
            field=models.ForeignKey(blank=True, help_text='Si se asigna, en POS pedirá categoría y temporada activa antes del equipo', null=True, on_delete=django.db.models.deletion.SET_NULL, to='league.categoria', verbose_name='Categoría'),
        ),
    ]
