# Generated by Django 6.0.5 on 2026-06-04 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_conceptoingreso_categoria'),
        ('league', '0045_equipo_campo_rancheria'),
    ]

    operations = [
        migrations.AddField(
            model_name='conceptoingreso',
            name='requiere_categoria',
            field=models.BooleanField(default=False, help_text='En POS pedirá categoría y temporada activa antes del equipo', verbose_name='Requiere categoría/temporada'),
        ),
        migrations.AlterField(
            model_name='conceptoingreso',
            name='categoria',
            field=models.ForeignKey(blank=True, help_text='Si se asigna, en POS filtra solo esta categoría (dejar vacío para todas)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='league.categoria', verbose_name='Categoría (filtro)'),
        ),
    ]
