# Generated by Django 6.0.5 on 2026-06-04 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_conceptoingreso_requiere_categoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conceptoingreso',
            name='excluir_pagados',
            field=models.BooleanField(default=False, help_text='En POS, al filtrar por temporada, oculta equipos que ya pagaron este concepto en esa temporada', verbose_name='Excluir pagados'),
        ),
    ]
