# Generated by Django 6.0.5 on 2026-05-27 04:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('telefono_contacto', models.CharField(blank=True, max_length=20)),
                ('precio_hora', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Campo',
                'verbose_name_plural': 'Campos',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('rango_edad', models.CharField(blank=True, max_length=50)),
                ('genero', models.CharField(blank=True, max_length=20)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
            },
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('color', models.CharField(blank=True, max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipos', to='league.categoria')),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
                'unique_together': {('nombre', 'categoria')},
            },
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='jugadores/')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('posicion', models.CharField(choices=[('POR', 'Portero'), ('DEF', 'Defensa'), ('MED', 'Mediocampista'), ('DEL', 'Delantero')], max_length=3)),
                ('dorsal', models.IntegerField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jugadores', to='league.equipo')),
            ],
            options={
                'verbose_name': 'Jugador',
                'verbose_name_plural': 'Jugadores',
            },
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField()),
                ('goles_local', models.IntegerField(default=0)),
                ('goles_visitante', models.IntegerField(default=0)),
                ('estado', models.CharField(choices=[('PEND', 'Pendiente'), ('JUG', 'Jugando'), ('FIN', 'Finalizado')], default='PEND', max_length=4)),
                ('campo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partidos', to='league.campo')),
                ('equipo_local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos_local', to='league.equipo')),
                ('equipo_visitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos_visitante', to='league.equipo')),
            ],
            options={
                'verbose_name': 'Partido',
                'verbose_name_plural': 'Partidos',
            },
        ),
        migrations.CreateModel(
            name='Gol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minuto', models.IntegerField()),
                ('tipo', models.CharField(choices=[('NORMAL', 'Normal'), ('PENAL', 'Penalti'), ('TIRO_LIBRE', 'Tiro Libre'), ('AUTOGOL', 'Autogol')], default='NORMAL', max_length=10)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goles', to='league.equipo')),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goles', to='league.jugador')),
                ('partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goles', to='league.partido')),
            ],
            options={
                'verbose_name': 'Gol',
                'verbose_name_plural': 'Goles',
            },
        ),
        migrations.CreateModel(
            name='Temporada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temporadas', to='league.categoria')),
            ],
            options={
                'verbose_name': 'Temporada',
                'verbose_name_plural': 'Temporadas',
            },
        ),
        migrations.AddField(
            model_name='partido',
            name='temporada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos', to='league.temporada'),
        ),
    ]
