# Generated by Django 6.0.5 on 2026-05-27 04:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporada',
            name='iniciada',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Jornada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('nombre', models.CharField(max_length=100)),
                ('temporada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jornadas', to='league.temporada')),
            ],
            options={
                'verbose_name': 'Jornada',
                'verbose_name_plural': 'Jornadas',
                'ordering': ['temporada', 'numero'],
                'unique_together': {('temporada', 'numero')},
            },
        ),
        migrations.AddField(
            model_name='partido',
            name='jornada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partidos', to='league.jornada'),
        ),
        migrations.CreateModel(
            name='PeriodoAltas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('fechas', 'Por rango de fechas'), ('jornadas', 'Por rango de jornadas')], max_length=10)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('jornada_inicio', models.IntegerField(blank=True, null=True)),
                ('jornada_fin', models.IntegerField(blank=True, null=True)),
                ('extraordinario', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('temporada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periodos_altas', to='league.temporada')),
            ],
            options={
                'verbose_name': 'Período de Altas',
                'verbose_name_plural': 'Períodos de Altas',
            },
        ),
    ]
