# Generated by Django 6.0.5 on 2026-05-27 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0002_temporada_iniciada_jornada_partido_jornada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='es_principal',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('AMARILLA', 'Tarjeta Amarilla'), ('ROJA', 'Tarjeta Roja')], max_length=10)),
                ('minuto', models.IntegerField()),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarjetas', to='league.equipo')),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarjetas', to='league.jugador')),
                ('partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarjetas', to='league.partido')),
            ],
            options={
                'verbose_name': 'Tarjeta',
                'verbose_name_plural': 'Tarjetas',
            },
        ),
        migrations.CreateModel(
            name='CampoDisponibilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jornada_numero', models.IntegerField()),
                ('disponible', models.BooleanField(default=True)),
                ('campo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.campo')),
                ('temporada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidad_campos', to='league.temporada')),
            ],
            options={
                'verbose_name': 'Disponibilidad de Campo',
                'verbose_name_plural': 'Disponibilidad de Campos',
                'unique_together': {('temporada', 'jornada_numero', 'campo')},
            },
        ),
    ]
