# Generated by Django 6.0.5 on 2026-05-27 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0003_categoria_es_principal_tarjeta_campodisponibilidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arbitro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Árbitro',
                'verbose_name_plural': 'Árbitros',
            },
        ),
        migrations.AddField(
            model_name='categoria',
            name='dias_juego',
            field=models.JSONField(blank=True, default=list, verbose_name='Días de juego'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='min_jugadores',
            field=models.IntegerField(default=7, verbose_name='Mínimo de jugadores por equipo'),
        ),
        migrations.AddField(
            model_name='partido',
            name='arbitro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partidos', to='league.arbitro'),
        ),
    ]
