# Generated by Django 6.0.5 on 2026-05-27 05:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0004_arbitro_categoria_dias_juego_categoria_min_jugadores_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionLiga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_liga', models.CharField(default='Mi Liga', max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='ligas/')),
                ('direccion', models.TextField(blank=True)),
                ('telefonos', models.TextField(blank=True, help_text='Teléfonos de contacto separados por coma')),
                ('email_smtp_host', models.CharField(blank=True, default='', max_length=200)),
                ('email_smtp_port', models.IntegerField(default=587)),
                ('email_smtp_user', models.CharField(blank=True, default='', max_length=200)),
                ('email_smtp_password', models.CharField(blank=True, default='', max_length=200)),
                ('email_from', models.EmailField(blank=True, default='', max_length=254)),
                ('email_use_tls', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Configuración de la Liga',
                'verbose_name_plural': 'Configuración de la Liga',
            },
        ),
        migrations.CreateModel(
            name='SuscripcionEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('recibir_roles', models.BooleanField(default=True, verbose_name='Recibir rol de juegos semanal')),
                ('recibir_estadisticas', models.BooleanField(default=True, verbose_name='Recibir estadísticas')),
                ('token', models.CharField(default=uuid.uuid4, editable=False, max_length=100, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('categorias', models.ManyToManyField(blank=True, to='league.categoria')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suscripciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Suscripción de Correo',
                'verbose_name_plural': 'Suscripciones de Correo',
            },
        ),
    ]
