# Generated by Django 6.0.5 on 2026-05-27 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0005_configuracionliga_suscripcionemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='max_jugadores',
            field=models.IntegerField(default=26, verbose_name='Máximo de jugadores por equipo'),
        ),
    ]
