# Generated by Django 6.0.5 on 2026-05-27 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0006_categoria_max_jugadores'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionliga',
            name='ticket_ancho_mm',
            field=models.IntegerField(choices=[(58, '58 mm'), (88, '88 mm')], default=58, verbose_name='Ancho del ticket (mm)'),
        ),
        migrations.AddField(
            model_name='configuracionliga',
            name='ticket_encabezado',
            field=models.TextField(blank=True, default='', help_text='Texto que aparece arriba del ticket (ej. nombre de la liga)', verbose_name='Encabezado del ticket'),
        ),
        migrations.AddField(
            model_name='configuracionliga',
            name='ticket_pie',
            field=models.TextField(blank=True, default='¡Gracias por su visita!', help_text='Texto al final del ticket (ej. Gracias por su visita)', verbose_name='Pie del ticket'),
        ),
    ]
