# Generated by Django 6.0.5 on 2026-05-27 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0007_configuracionliga_ticket_ancho_mm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='horarios',
            field=models.JSONField(blank=True, default=list, verbose_name='Horarios (HH:MM)'),
        ),
        migrations.AlterField(
            model_name='partido',
            name='estado',
            field=models.CharField(choices=[('PEND', 'Pendiente'), ('SUSP', 'Suspendido'), ('JUG', 'Jugando'), ('FIN', 'Finalizado')], default='PEND', max_length=4),
        ),
        migrations.CreateModel(
            name='HorarioFijoEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario', models.CharField(max_length=5, verbose_name='Horario (HH:MM)')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios_fijos', to='league.equipo')),
                ('temporada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios_fijos', to='league.temporada')),
            ],
            options={
                'verbose_name': 'Horario Fijo de Equipo',
                'verbose_name_plural': 'Horarios Fijos de Equipos',
                'unique_together': {('temporada', 'equipo')},
            },
        ),
    ]
