# Generated by Django 6.0.5 on 2026-05-27 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0008_categoria_horarios_alter_partido_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partido',
            name='observaciones',
            field=models.TextField(blank=True, verbose_name='Observaciones'),
        ),
    ]
