# Generated by Django 6.0.5 on 2026-05-27 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0009_partido_observaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporada',
            name='num_grupos',
            field=models.IntegerField(default=0, verbose_name='Número de grupos (solo para Por Grupos)'),
        ),
        migrations.AddField(
            model_name='temporada',
            name='tipo_rol',
            field=models.CharField(choices=[('TODOS', 'Todos contra Todos'), ('GRUPOS', 'Por Grupos')], default='TODOS', max_length=10, verbose_name='Tipo de rol'),
        ),
        migrations.AddField(
            model_name='temporada',
            name='vueltas',
            field=models.IntegerField(default=1, verbose_name='Número de vueltas'),
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.CharField(max_length=10, verbose_name='Grupo (A, B, C...)')),
                ('orden', models.IntegerField(default=0)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos', to='league.equipo')),
                ('temporada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos', to='league.temporada')),
            ],
            options={
                'verbose_name': 'Grupo',
                'verbose_name_plural': 'Grupos',
                'ordering': ['grupo', 'orden'],
                'unique_together': {('temporada', 'equipo')},
            },
        ),
    ]
