# Generated by Django 6.0.5 on 2026-05-27 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0010_temporada_num_grupos_temporada_tipo_rol_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='categorias_compatibles',
            field=models.ManyToManyField(blank=True, help_text='Jugadores de esta categoría también pueden registrarse en las categorías seleccionadas.', to='league.categoria', verbose_name='Categorías compatibles'),
        ),
    ]
