# Generated by Django 6.0.5 on 2026-05-27 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0011_categoria_categorias_compatibles'),
    ]

    operations = [
        migrations.AddField(
            model_name='campo',
            name='es_rancheria',
            field=models.BooleanField(default=False, verbose_name='Es ranchería'),
        ),
    ]
