# Generated by Django 6.0.5 on 2026-05-27 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0012_campo_es_rancheria'),
    ]

    operations = [
        migrations.AddField(
            model_name='campo',
            name='fecha_estimada_retorno',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha estimada de retorno'),
        ),
        migrations.AddField(
            model_name='campo',
            name='observaciones',
            field=models.TextField(blank=True, verbose_name='Observaciones'),
        ),
    ]
