# Generated by Django 6.0.5 on 2026-05-28 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0013_campo_fecha_estimada_retorno_campo_observaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporada',
            name='fecha_finalizacion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de finalización'),
        ),
        migrations.AddField(
            model_name='temporada',
            name='finalizada',
            field=models.BooleanField(default=False, verbose_name='Finalizada'),
        ),
        migrations.AddField(
            model_name='temporada',
            name='motivo_finalizacion',
            field=models.TextField(blank=True, verbose_name='Motivo de finalización'),
        ),
    ]
