# Generated by Django 6.0.5 on 2026-05-28 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0014_temporada_fecha_finalizacion_temporada_finalizada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partido',
            name='es_liguilla',
            field=models.BooleanField(default=False, verbose_name='Es partido de liguilla'),
        ),
        migrations.AddField(
            model_name='temporada',
            name='num_clasificados',
            field=models.IntegerField(default=8, verbose_name='Clasificados a liguilla (solo para Liguilla)'),
        ),
        migrations.AddField(
            model_name='temporada',
            name='tipo_competencia',
            field=models.CharField(choices=[('PUNTOS', 'Por puntos (más puntos gana)'), ('LIGUILLA', 'Liguilla (clasifican los mejores)')], default='PUNTOS', max_length=10, verbose_name='Tipo de competencia'),
        ),
    ]
