# Generated by Django 6.0.5 on 2026-05-28 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0015_partido_es_liguilla_temporada_num_clasificados_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporada',
            name='es_prueba',
            field=models.BooleanField(default=False, verbose_name='Modo prueba'),
        ),
    ]
