# Generated by Django 6.0.5 on 2026-05-28 02:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0016_temporada_es_prueba'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporada',
            name='jornadas_limite_pago',
            field=models.IntegerField(blank=True, help_text='Si un equipo no ha pagado la inscripción después de esta jornada, pierde por default hasta que pague.', null=True, verbose_name='Jornadas límite para pago de inscripción'),
        ),
        migrations.CreateModel(
            name='AbandonoTemporada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abandonos', to='league.equipo')),
                ('temporada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abandonos', to='league.temporada')),
            ],
            options={
                'verbose_name': 'Abandono de Temporada',
                'verbose_name_plural': 'Abandonos de Temporada',
                'unique_together': {('temporada', 'equipo')},
            },
        ),
    ]
