# Generated by Django 6.0.5 on 2026-05-28 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0017_temporada_jornadas_limite_pago_abandonotemporada'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarjeta',
            name='suspension_jornadas',
            field=models.IntegerField(default=0, verbose_name='Jornadas de suspensión'),
        ),
    ]
