# Generated by Django 6.0.5 on 2026-05-28 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0018_tarjeta_suspension_jornadas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipo',
            name='color',
        ),
    ]
