# Generated by Django 6.0.5 on 2026-05-28 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0019_remove_equipo_color'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CampoDisponibilidad',
        ),
    ]
