# Generated by Django 6.0.5 on 2026-05-28 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0020_delete_campodisponibilidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampoIndisponibilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_desde', models.DateField()),
                ('fecha_hasta', models.DateField()),
                ('motivo', models.TextField(blank=True, verbose_name='Motivo')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('campo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indisponibilidades', to='league.campo')),
            ],
            options={
                'verbose_name': 'Indisponibilidad de Campo',
                'verbose_name_plural': 'Indisponibilidades de Campos',
                'ordering': ['-fecha_desde'],
            },
        ),
    ]
