# Generated by Django 6.0.5 on 2026-05-28 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0021_campoindisponibilidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='JugadorPartido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titular', models.BooleanField(default=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.equipo')),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.jugador')),
                ('partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participaciones', to='league.partido')),
            ],
            options={
                'verbose_name': 'Participación de Jugador',
                'verbose_name_plural': 'Participaciones de Jugadores',
                'unique_together': {('partido', 'jugador')},
            },
        ),
    ]
