# Generated by Django 6.0.5 on 2026-05-28 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0022_jugadorpartido'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporada',
            name='goles_default',
            field=models.IntegerField(default=3, help_text='Goles que se le asignan al equipo que gana por default (ej. 3-0).', verbose_name='Goles por default'),
        ),
    ]
