# Generated by Django 6.0.5 on 2026-05-28 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0023_temporada_goles_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='partido',
            name='default_team',
            field=models.CharField(blank=True, choices=[('local', 'Local'), ('visitante', 'Visitante')], max_length=10, null=True, verbose_name='Perdió por default'),
        ),
        migrations.AddField(
            model_name='partido',
            name='motivo_default',
            field=models.TextField(blank=True, verbose_name='Motivo del default'),
        ),
    ]
