# Generated by Django 6.0.5 on 2026-05-28 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0024_partido_default_team_partido_motivo_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionliga',
            name='correo_electronico',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='Correo electrónico de contacto'),
        ),
        migrations.AddField(
            model_name='configuracionliga',
            name='redes_sociales',
            field=models.TextField(blank=True, default='', help_text='Enlaces a redes sociales (uno por línea)', verbose_name='Redes sociales'),
        ),
    ]
