# Generated by Django 6.0.5 on 2026-05-28 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0025_configuracionliga_correo_electronico_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionliga',
            name='facebook_access_token',
            field=models.CharField(blank=True, default='', help_text="Token de página de Facebook Graph API. Para obtenerlo: 1) Crea una App en https://developers.facebook.com, 2) Ve a 'Graph API Explorer', selecciona tu app y página, 3) Genera un Page Access Token con permisos 'pages_manage_posts' y 'pages_read_engagement'.", max_length=500, verbose_name='Access Token de Facebook'),
        ),
        migrations.AddField(
            model_name='configuracionliga',
            name='facebook_page_id',
            field=models.CharField(blank=True, default='', help_text="Ej: 123456789012345 (lo encuentras en la sección 'About' de tu página de Facebook)", max_length=200, verbose_name='ID de página de Facebook'),
        ),
    ]
