# Generated by Django 6.0.5 on 2026-05-28 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0026_configuracionliga_facebook_access_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporada',
            name='min_jugadores',
            field=models.IntegerField(default=7, help_text='Número mínimo de jugadores que debe tener un equipo en cédula para poder jugar. Si no se cumple, solo se puede guardar como Default.', verbose_name='Mínimo de jugadores por equipo'),
        ),
    ]
