# Generated by Django 6.0.5 on 2026-05-28 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0027_temporada_min_jugadores'),
    ]

    operations = [
        migrations.AddField(
            model_name='partido',
            name='default_visitante',
            field=models.BooleanField(default=False, verbose_name='Visitante pierde por default'),
        ),
        migrations.AlterField(
            model_name='partido',
            name='default_team',
            field=models.CharField(blank=True, choices=[('local', 'Local'), ('visitante', 'Visitante')], max_length=10, null=True, verbose_name='Local pierde por default (obsoleto)'),
        ),
    ]
