# Generated by Django 6.0.5 on 2026-05-28 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0028_partido_default_visitante_alter_partido_default_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporada',
            name='cambios_permitidos',
            field=models.IntegerField(default=5, help_text='Número máximo de cambios (suplentes) permitidos por equipo por partido.', verbose_name='Cambios permitidos por equipo'),
        ),
    ]
