# Generated by Django 6.0.5 on 2026-05-30 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0029_temporada_cambios_permitidos'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionliga',
            name='enviar_solo_jornada_actual',
            field=models.BooleanField(default=False, help_text='Al enviar roles por correo, enviar solo los partidos de la jornada actual o próxima pendiente', verbose_name='Enviar solo la jornada actual'),
        ),
    ]
