# Generated by Django 6.0.5 on 2026-05-30 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0030_configuracionliga_envio_automatico'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporada',
            name='max_titulares',
            field=models.IntegerField(default=11, help_text='Número máximo de jugadores titulares permitidos por equipo en la cédula. Si se excede, el partido se pierde por default por alineación indebida.', verbose_name='Máximo de titulares por equipo'),
        ),
    ]
