# Generated by Django 6.0.5 on 2026-05-31 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0031_temporada_max_titulares'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporada',
            name='gol_visitante_desempate',
            field=models.BooleanField(default=False, help_text='Usa los goles como visitante como 4° criterio de desempate en la tabla general.', verbose_name='Gol de visitante como desempate'),
        ),
        migrations.AddField(
            model_name='temporada',
            name='ida_vuelta',
            field=models.BooleanField(default=False, help_text='Si está activo, los cruces de liguilla serán a dos partidos (ida y vuelta).', verbose_name='Liguilla a ida y vuelta'),
        ),
        migrations.AddField(
            model_name='temporada',
            name='posicion_tabla_desempate',
            field=models.BooleanField(default=False, help_text='Si hay empate en todos los criterios, se usa el resultado del partido entre los equipos empatados.', verbose_name='Enfrentamiento directo como desempate'),
        ),
    ]
