# Generated by Django 6.0.5 on 2026-06-01 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0032_temporada_gol_visitante_desempate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporada',
            name='final_ida_vuelta',
            field=models.BooleanField(default=False, help_text='Si está activo, la final será a dos partidos (ida y vuelta).', verbose_name='Final a ida y vuelta'),
        ),
    ]
