# Generated by Django 6.0.5 on 2026-06-01 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0033_temporada_final_ida_vuelta'),
    ]

    operations = [
        migrations.AddField(
            model_name='partido',
            name='liguilla_leg',
            field=models.IntegerField(blank=True, null=True, verbose_name='Partido de liguilla (1=ida, 2=vuelta)'),
        ),
    ]
