# Generated by Django 6.0.5 on 2026-06-01 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0034_partido_liguilla_leg'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporada',
            name='gol_visitante_liguilla',
            field=models.BooleanField(default=False, help_text='Si hay empate global en una serie de liguilla, se usa el número de goles de visitante como criterio.', verbose_name='Gol de visitante como desempate en liguilla'),
        ),
        migrations.AddField(
            model_name='temporada',
            name='posicion_tabla_liguilla',
            field=models.BooleanField(default=False, help_text='Si hay empate global en una serie de liguilla, avanza el mejor posicionado en la tabla general.', verbose_name='Posición en la tabla como desempate en liguilla'),
        ),
    ]
