# Generated by Django 6.0.5 on 2026-06-01 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0035_temporada_gol_visitante_liguilla_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temporada',
            name='gol_visitante_liguilla',
        ),
        migrations.RemoveField(
            model_name='temporada',
            name='posicion_tabla_liguilla',
        ),
        migrations.AddField(
            model_name='temporada',
            name='criterio_liguilla',
            field=models.CharField(blank=True, choices=[('gol_visitante', 'Gol de visitante'), ('posicion_tabla', 'Posición en la tabla')], help_text='Si hay empate global en una serie de liguilla, ¿qué criterio usar para definir al ganador?', max_length=20, null=True, verbose_name='Criterio de desempate en liguilla'),
        ),
    ]
