# Generated by Django 6.0.5 on 2026-06-01 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0036_remove_temporada_gol_visitante_liguilla_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JugadorEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_principal', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_alta', models.DateField(auto_now_add=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_jugador', to='league.equipo')),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_equipo', to='league.jugador')),
            ],
            options={
                'verbose_name': 'Registro Jugador-Equipo',
                'verbose_name_plural': 'Registros Jugador-Equipo',
                'unique_together': {('jugador', 'equipo')},
            },
        ),
        migrations.AddField(
            model_name='jugador',
            name='equipos',
            field=models.ManyToManyField(blank=True, related_name='jugadores_m2m', through='league.JugadorEquipo', to='league.equipo', verbose_name='Equipos (compatibles)'),
        ),
    ]
