# Generated by Django 6.0.5 on 2026-06-01 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0037_jugadorequipo_jugador_equipos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='periodoaltas',
            options={'verbose_name': 'Período de Altas/Bajas', 'verbose_name_plural': 'Períodos de Altas/Bajas'},
        ),
        migrations.AddField(
            model_name='categoria',
            name='edad_maxima',
            field=models.IntegerField(blank=True, help_text='Edad máxima permitida (dejar vacío si no aplica)', null=True, verbose_name='Edad máxima'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='edad_minima',
            field=models.IntegerField(blank=True, help_text='Edad mínima requerida (dejar vacío si no aplica)', null=True, verbose_name='Edad mínima'),
        ),
    ]
