# Generated by Django 6.0.5 on 2026-06-01 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0038_alter_periodoaltas_options_categoria_edad_maxima_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='suspendido_pago',
            field=models.BooleanField(default=False, help_text='Suspendido por multa de edad. Se levanta al registrar el pago.', verbose_name='Suspendido por multa'),
        ),
    ]
