# Generated by Django 6.0.5 on 2026-06-02 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0039_jugador_suspendido_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='curp',
            field=models.CharField(blank=True, help_text='Clave Única de Registro de Población (18 caracteres)', max_length=18, null=True, unique=True, verbose_name='CURP'),
        ),
    ]
