# Generated by Django 6.0.5 on 2026-06-02 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0040_jugador_curp'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporada',
            name='min_porcentaje_liguilla',
            field=models.IntegerField(blank=True, help_text='Porcentaje de partidos de temporada regular que un jugador debe haber jugado para ser elegible en liguilla. Vacío = sin restricción.', null=True, verbose_name='% mínimo de juegos para liguilla'),
        ),
    ]
