# Generated by Django 6.0.5 on 2026-06-04 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0041_temporada_min_porcentaje_liguilla'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporada',
            name='clasificacion_por_grupos',
            field=models.BooleanField(default=False, help_text="Si está activo, clasifican los mejores de cada grupo en lugar de la tabla general. Solo aplica cuando el rol es 'Por Grupos'.", verbose_name='Clasificar por grupos'),
        ),
    ]
