# Generated by Django 6.0.5 on 2026-06-04 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0042_temporada_clasificacion_por_grupos'),
    ]

    operations = [
        migrations.AddField(
            model_name='partido',
            name='grupo',
            field=models.CharField(blank=True, max_length=1, verbose_name='Grupo'),
        ),
    ]
