# Generated by Django 6.0.5 on 2026-06-04 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0044_arbitro_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='campo_rancheria',
            field=models.ForeignKey(blank=True, help_text='Si es equipo de ranchería, selecciona su campo. Cuando sea local se asignará automáticamente.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='league.campo', verbose_name='Campo ranchería'),
        ),
    ]
