# Generated by Django 6.0.5 on 2026-06-05 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0045_equipo_campo_rancheria'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='campo_exclusivo',
            field=models.ForeignKey(blank=True, help_text='Si esta categoría juega siempre en un mismo campo, selecciónalo aquí.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='league.campo', verbose_name='Campo exclusivo'),
        ),
    ]
