# Generated by Django 6.0.5 on 2026-06-05 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0046_campo_exclusivo_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='campos_permitidos',
            field=models.ManyToManyField(blank=True, help_text='Únicos campos donde puede jugar esta categoría. Si no seleccionas ninguno, puede jugar en cualquier campo.', related_name='categorias_permitidas', to='league.campo', verbose_name='Campos permitidos'),
        ),
    ]
