# Generated by Django 6.0.5 on 2026-06-05 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0047_campos_permitidos_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='campo_exclusivo',
        ),
    ]
