# Generated by Django 6.0.5 on 2026-06-09 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0048_campos_permitidos'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionliga',
            name='email_provider',
            field=models.CharField(choices=[('google', 'Google SMTP'), ('sendgrid', 'SendGrid')], default='google', max_length=20, verbose_name='Proveedor de correo'),
        ),
        migrations.AddField(
            model_name='configuracionliga',
            name='email_sendgrid_host',
            field=models.CharField(blank=True, default='smtp.sendgrid.net', max_length=200),
        ),
        migrations.AddField(
            model_name='configuracionliga',
            name='email_sendgrid_password',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='configuracionliga',
            name='email_sendgrid_port',
            field=models.IntegerField(default=587),
        ),
        migrations.AddField(
            model_name='configuracionliga',
            name='email_sendgrid_use_tls',
            field=models.BooleanField(default=True, verbose_name='Usar TLS (SendGrid)'),
        ),
        migrations.AddField(
            model_name='configuracionliga',
            name='email_sendgrid_user',
            field=models.CharField(blank=True, default='apikey', max_length=200),
        ),
    ]
