# Generated by Django 6.0.5 on 2026-06-16 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0049_configuracionliga_email_provider_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='fondo_credencial',
            field=models.ImageField(blank=True, help_text='Imagen de fondo que aparecerá en las credenciales de esta categoría.', null=True, upload_to='fondos_credencial/', verbose_name='Fondo para credenciales'),
        ),
    ]
