# Generated by Django 6.0.6 on 2026-06-17 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0050_categoria_fondo_credencial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jornada',
            name='estado',
            field=models.CharField(choices=[('ACTIVA', 'Activa'), ('SUSPENDIDA', 'Suspendida')], default='ACTIVA', max_length=10),
        ),
        migrations.AddField(
            model_name='jornada',
            name='motivo_suspension',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='jornada',
            name='semanas_suspension',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
