# Generated by Django 6.0.6 on 2026-06-23 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0052_devicetoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='partido',
            name='recordatorio_30min_enviado',
            field=models.BooleanField(default=False, verbose_name='Recordatorio 30min enviado'),
        ),
    ]
