# Generated by Django 6.0.6 on 2026-06-23 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0053_partido_recordatorio_30min_enviado'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicetoken',
            name='categorias',
            field=models.ManyToManyField(blank=True, help_text='Categorías sobre las que quiere recibir notificaciones', to='league.categoria', verbose_name='Categorías de interés'),
        ),
        migrations.AddField(
            model_name='devicetoken',
            name='es_invitado',
            field=models.BooleanField(default=False, help_text='Registrado como invitado sin cuenta completa', verbose_name='Es invitado'),
        ),
        migrations.AddField(
            model_name='devicetoken',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nombre o apodo'),
        ),
        migrations.AddField(
            model_name='devicetoken',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, verbose_name='Teléfono'),
        ),
    ]
