# Generated by Django 6.0.6 on 2026-06-24 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0054_devicetoken_categorias_devicetoken_es_invitado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PushLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(choices=[('SEND', 'Envío directo'), ('PARTIDO_FIN', 'Partido finalizado'), ('RECORDATORIO', 'Recordatorio 30 min')], max_length=20)),
                ('partido_id', models.IntegerField(blank=True, null=True)),
                ('categoria', models.CharField(blank=True, max_length=200)),
                ('total_activos', models.IntegerField(blank=True, null=True)),
                ('tokens_encontrados', models.IntegerField(blank=True, null=True)),
                ('guests_incluidos', models.IntegerField(blank=True, null=True)),
                ('success', models.IntegerField(blank=True, null=True)),
                ('failure', models.IntegerField(blank=True, null=True)),
                ('detalle', models.TextField(blank=True)),
                ('error', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Log de Push',
                'verbose_name_plural': 'Logs de Push',
                'ordering': ['-hora'],
            },
        ),
    ]
