# Generated by Django 6.0.6 on 2026-06-24 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0055_pushlog_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicetoken',
            name='device_id',
            field=models.CharField(blank=True, db_index=True, help_text='UUID generado por el cliente para identificar el dispositivo', max_length=36, verbose_name='ID de dispositivo'),
        ),
    ]
