# Generated by Django 6.0.6 on 2026-06-24 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0056_devicetoken_device_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicetoken',
            name='device_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='UUID generado por el cliente para identificar el dispositivo', max_length=36, null=True, verbose_name='ID de dispositivo'),
        ),
    ]
