# Generated by Django 6.0.6 on 2026-06-25 04:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0057_devicetoken_device_id_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='partido',
            name='es_amistoso',
            field=models.BooleanField(default=False, verbose_name='Es partido amistoso'),
        ),
        migrations.AlterField(
            model_name='partido',
            name='temporada',
            field=models.ForeignKey(blank=True, help_text='Obligatorio para partidos de liga. Déjalo vacío para partidos amistosos.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partidos', to='league.temporada'),
        ),
    ]
