# Generated by Django 6.0.6 on 2026-07-25 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0058_partido_amistoso'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionliga',
            name='reglamento',
            field=models.FileField(blank=True, help_text='Archivo PDF del reglamento de la liga. Visible para todos los usuarios.', null=True, upload_to='reglamentos/', verbose_name='Reglamento (PDF)'),
        ),
    ]
