# Generated by Django 6.0.6 on 2026-07-25 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0059_reglamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionliga',
            name='cloudinary_api_key',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Cloudinary API Key'),
        ),
        migrations.AddField(
            model_name='configuracionliga',
            name='cloudinary_api_secret',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Cloudinary API Secret'),
        ),
        migrations.AddField(
            model_name='configuracionliga',
            name='cloudinary_cloud_name',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Cloudinary Cloud Name'),
        ),
        migrations.AddField(
            model_name='configuracionliga',
            name='database_url',
            field=models.URLField(blank=True, default='', help_text='URL completa de conexión a la base de datos. Ej: postgresql://user:pass@host/db?sslmode=require. Requiere reiniciar el servidor tras cambiar.', max_length=500, verbose_name='Database URL'),
        ),
    ]
