# Generated by Django 6.0.6 on 2026-07-27 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0060_infra_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionliga',
            name='firebase_service_account_json',
            field=models.TextField(blank=True, default='', help_text='Pega aquí el JSON completo de la service account de Firebase. Se usa para enviar notificaciones push.', verbose_name='Firebase Service Account JSON'),
        ),
    ]
