# Generated by Django 6.0.6 on 2026-08-01 00:33

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0063_offlinetoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracionliga',
            name='apk_file',
            field=models.FileField(blank=True, help_text='APK firmada de la app. Descargable por todos los usuarios desde el menú. Se guarda en el servidor (no requiere Cloudinary).', null=True, storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\lodo1\\Desktop\\PROYECTOS\\PROYECTOS\\Personal\\AdminFut\\media\\apks'), upload_to='', verbose_name='App Android (APK)'),
        ),
    ]
