# Generated by Django 6.0.6 on 2026-08-01 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0064_alter_configuracionliga_apk_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracionliga',
            name='apk_file',
            field=models.FileField(blank=True, help_text='APK firmada de la app. Descargable por todos los usuarios desde el menú. Se guarda en Cloudinary (sobrevive a redeploys).', null=True, upload_to='apk', verbose_name='App Android (APK)'),
        ),
    ]
