# Generated by Django 6.0.6 on 2026-08-01 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0065_alter_configuracionliga_apk_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracionliga',
            name='apk_file',
        ),
    ]
