# Generated by Django 6.0.6 on 2026-08-01 04:52

import league.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0066_remove_configuracionliga_apk_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracionliga',
            name='reglamento',
            field=models.FileField(blank=True, help_text='Archivo PDF del reglamento de la liga. Visible para todos los usuarios.', null=True, storage=league.models.RawCloudinaryStorage(folder='reglamentos'), upload_to='reglamentos/', verbose_name='Reglamento (PDF)'),
        ),
    ]
