# Generated by Django 6.0.6 on 2026-08-03 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0067_alter_configuracionliga_reglamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionliga',
            name='segunda_linea',
            field=models.CharField(blank=True, default='', help_text="Opcional. Se muestra centrado bajo el nombre (ej: 'Juventino Rosas'). Si se deja vacío se divide el nombre automáticamente.", max_length=200, verbose_name='Segunda línea del nombre'),
        ),
    ]
