# Generated by Django 6.0.6 on 2026-08-03 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0068_configuracionliga_segunda_linea'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='curp_obligatoria',
            field=models.BooleanField(default=False, help_text='Si está activa, el CURP será obligatorio al registrar jugadores en esta categoría.', verbose_name='CURP obligatoria'),
        ),
    ]
