# Generated by Django 6.0.6 on 2026-08-03 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0069_categoria_curp_obligatoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicetoken',
            name='email',
            field=models.EmailField(blank=True, default='', help_text='Si se captura, el invitado también recibe por correo el rol de juegos de sus categorías', max_length=254, verbose_name='Correo'),
        ),
    ]
