# Generated by Django 6.0.6 on 2026-08-03 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0071_merge_duplicate_devices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pushlog',
            name='tipo',
            field=models.CharField(choices=[('SEND', 'Envío directo'), ('PARTIDO_FIN', 'Partido finalizado'), ('RECORDATORIO', 'Recordatorio 30 min'), ('SUSPENSION', 'Suspensión / pendiente')], max_length=20),
        ),
    ]
