# Generated by Django 6.0.6 on 2026-08-03 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0072_alter_pushlog_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionliga',
            name='webpush_vapid_private_key',
            field=models.TextField(blank=True, default='', help_text='Clave privada VAPID para notificaciones Web Push (PWA). Se genera automáticamente; no compartir.', verbose_name='Clave privada VAPID (Web Push)'),
        ),
        migrations.AddField(
            model_name='configuracionliga',
            name='webpush_vapid_public_key',
            field=models.TextField(blank=True, default='', help_text='Clave pública VAPID (applicationServerKey) que usan los navegadores al suscribirse a notificaciones Web Push. Se genera automáticamente.', verbose_name='Clave pública VAPID (Web Push)'),
        ),
        migrations.AddField(
            model_name='devicetoken',
            name='webpush_auth',
            field=models.TextField(blank=True, default='', help_text='Secreto de autenticación de la suscripción Web Push', verbose_name='Clave auth (Web Push)'),
        ),
        migrations.AddField(
            model_name='devicetoken',
            name='webpush_endpoint',
            field=models.TextField(blank=True, default='', help_text='Endpoint de suscripción Web Push del navegador (PWA / iPhone)', verbose_name='Endpoint Web Push'),
        ),
        migrations.AddField(
            model_name='devicetoken',
            name='webpush_p256dh',
            field=models.TextField(blank=True, default='', help_text='Clave pública de cifrado de la suscripción Web Push', verbose_name='Clave p256dh (Web Push)'),
        ),
        migrations.AlterField(
            model_name='devicetoken',
            name='plataforma',
            field=models.CharField(choices=[('android', 'Android'), ('ios', 'iOS'), ('web', 'Web'), ('pwa', 'PWA / Web Push')], default='android', max_length=10),
        ),
        migrations.AlterField(
            model_name='pushlog',
            name='tipo',
            field=models.CharField(choices=[('SEND', 'Envío directo'), ('PARTIDO_FIN', 'Partido finalizado'), ('RECORDATORIO', 'Recordatorio 30 min'), ('SUSPENSION', 'Suspensión / pendiente'), ('WEBPUSH', 'Web Push (PWA)')], max_length=20),
        ),
    ]
