# Generated by Django 6.0.6 on 2026-08-06 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0073_configuracionliga_webpush_vapid_private_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='tipo_documento',
            field=models.CharField(choices=[('CURP', 'CURP'), ('PAS', 'Pasaporte'), ('INM', 'Cédula INM / Residencia'), ('OTR', 'Otro')], default='CURP', help_text='CURP para mexicanos. Para extranjeros: Pasaporte o Cédula INM.', max_length=4, verbose_name='Tipo de documento'),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='curp',
            field=models.CharField(blank=True, help_text='CURP (18 caracteres) o número de pasaporte/INM según el tipo.', max_length=18, null=True, unique=True, verbose_name='Número de documento'),
        ),
    ]
