# Generated by Django 6.0.5 on 2026-09-05 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0074_jugador_tipo_documento_alter_jugador_curp'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporada',
            name='puntos_default',
            field=models.IntegerField(default=6, help_text='Puntos que se restan al equipo que pierde un partido por default (mora, abandono o alineación indebida). Ej. 6 = -6 puntos en la tabla por cada partido perdido por default.', verbose_name='Puntos que pierde por derrota default'),
        ),
    ]
