# Generated by Django 6.0.5 on 2026-09-07 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0075_temporada_puntos_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuspensionJugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jornadas', models.PositiveIntegerField(default=1, verbose_name='Jornadas de suspensión')),
                ('motivo', models.TextField(blank=True, verbose_name='Motivo')),
                ('activo', models.BooleanField(default=True, verbose_name='Activa')),
                ('fecha_inicio', models.DateField(verbose_name='Inicio del conteo')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='suspensiones_manuales', to='league.categoria')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suspensiones_manuales', to='league.equipo')),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suspensiones_manuales', to='league.jugador')),
                ('temporada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suspensiones_manuales', to='league.temporada', verbose_name='Temporada donde inicia')),
            ],
            options={
                'verbose_name': 'Suspensión manual',
                'verbose_name_plural': 'Suspensiones manuales',
                'ordering': ['-creado'],
            },
        ),
    ]
