# Generated by Django 6.0.5 on 2026-09-07 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0076_suspensionjugador'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='nivel',
            field=models.PositiveIntegerField(blank=True, help_text='Orden de la escalera: 1 es la categoría más alta (ej. Primera), 2 la siguiente (Intermedia), 3 la más baja (Segunda). Se usa para ascensos/descensos.', null=True, verbose_name='Nivel (ascenso/descenso)'),
        ),
        migrations.AddField(
            model_name='temporada',
            name='aplicar_movimientos',
            field=models.BooleanField(default=True, help_text='Si está activo, al finalizar la temporada se piden los movimientos (sube/baja/desaparece) y se aplican las restricciones a los jugadores. Desactívalo cuando no se quiera mover equipos.', verbose_name='Aplicar reglas de ascenso/descenso'),
        ),
        migrations.AddField(
            model_name='temporada',
            name='num_ascensos',
            field=models.PositiveIntegerField(default=2, help_text='Cuántos equipos suben de categoría al finalizar esta temporada (campeón + los mejores del lugar).', verbose_name='Equipos que ascienden'),
        ),
        migrations.AddField(
            model_name='temporada',
            name='num_descensos',
            field=models.PositiveIntegerField(default=2, help_text='Cuántos equipos bajan de categoría al finalizar esta temporada (los últimos lugares de la tabla).', verbose_name='Equipos que descienden'),
        ),
        migrations.CreateModel(
            name='MovimientoEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ASCENSO', 'Asciende'), ('DESCENSO', 'Desciende'), ('DESAPARECE', 'Desaparece'), ('SE_QUEDA', 'Se queda')], max_length=12)),
                ('jugadores_plantilla', models.PositiveIntegerField(default=0, help_text='Tamaño de la plantilla del equipo cuando se registró el movimiento (referencia para el 50% en ascensos).', verbose_name='Jugadores en plantilla al cierre')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('destino_categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_destino', to='league.categoria')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='league.equipo')),
                ('origen_categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_origen', to='league.categoria')),
                ('temporada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_equipos', to='league.temporada')),
            ],
            options={
                'verbose_name': 'Movimiento de equipo',
                'verbose_name_plural': 'Movimientos de equipos',
                'ordering': ['-temporada__fecha_inicio', 'equipo__nombre'],
                'unique_together': {('temporada', 'equipo')},
            },
        ),
    ]
