# Generated by Django 6.0.6 on 2026-09-08 00:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0077_categoria_nivel_temporada_aplicar_movimientos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientoequipo',
            name='cupo_porcentaje',
            field=models.PositiveIntegerField(default=50, help_text='Porcentaje de la plantilla que puede cambiarse a otro equipo en un ascenso (50% por defecto). Ajusta si uno de los torneos ya pasó y sólo resta un cupo menor o la regla ya se cumplió.', verbose_name='Cupo de transferencia (%)'),
        ),
        migrations.AddField(
            model_name='movimientoequipo',
            name='regla_activa',
            field=models.BooleanField(default=True, help_text='Mientras esté activa, los jugadores de este equipo quedan restringidos por este movimiento. Desactívala cuando los torneos (Copa/Liga) para los que aplicaba ya hayan pasado.', verbose_name='Vigencia de la regla'),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='equipo',
            field=models.ForeignKey(blank=True, help_text='Equipo principal. Puede dejarse vacío si el jugador aún no tiene equipo asignado.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jugadores', to='league.equipo'),
        ),
        migrations.AlterField(
            model_name='movimientoequipo',
            name='jugadores_plantilla',
            field=models.PositiveIntegerField(default=0, help_text='Tamaño de la plantilla del equipo cuando se registró el movimiento (referencia para el cupo de transferencia en ascensos).', verbose_name='Jugadores en plantilla al cierre'),
        ),
        migrations.AlterField(
            model_name='suspensionjugador',
            name='equipo',
            field=models.ForeignKey(blank=True, help_text='Opcional. Si se deja vacío, la suspensión cuenta las jornadas de toda la categoría.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suspensiones_manuales', to='league.equipo', verbose_name='Equipo (rol donde cumple)'),
        ),
    ]
