# Generated by Django 6.0.6 on 2026-09-08 02:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0078_movimientoequipo_cupo_porcentaje_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JugadorHerencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CASTIGADO', 'Castigado (expulsado del equipo)'), ('ASCENSO', 'Ascendido (desde otra categoría)'), ('DESCENSO', 'Descendido (desde otra categoría)'), ('DESAPARECE', 'Equipo se dio de baja')], max_length=12)),
                ('jornadas', models.PositiveIntegerField(default=0, help_text='Opcional: jornadas que le faltan de cumplir. Si se pone un número mayor a 0, se crea una suspensión que bloquea al jugador en toda la liga.', verbose_name='Jornadas de castigo restantes')),
                ('motivo', models.TextField(blank=True, verbose_name='Motivo')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(help_text='Categoría donde se castigó / ascendió / descendió / se dio de baja.', on_delete=django.db.models.deletion.PROTECT, related_name='jugadores_heredados', to='league.categoria', verbose_name='Categoría del evento')),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='herencia', to='league.jugador')),
            ],
            options={
                'verbose_name': 'Jugador heredado',
                'verbose_name_plural': 'Jugadores heredados',
                'ordering': ['-creado'],
            },
        ),
    ]
