# Generated by Django 6.0.6 on 2026-09-09 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0083_baja_registros_incompatibles_heredados'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporada',
            name='cambios_permitidos',
            field=models.IntegerField(blank=True, default=5, help_text='Máximo de cambios (suplentes) permitidos por equipo por partido. Déjalo en blanco o pon 0 para no limitar los cambios (sin restricción).', null=True, verbose_name='Cambios permitidos por equipo'),
        ),
    ]
