# Generated by Django 6.0.6 on 2026-09-09 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0084_alter_temporada_cambios_permitidos'),
    ]

    operations = [
        migrations.AddField(
            model_name='suspensionjugador',
            name='vitalicia',
            field=models.BooleanField(default=False, help_text='Si está activa, la suspensión nunca expira (expulsión de por vida).', verbose_name='De por vida'),
        ),
        migrations.AlterField(
            model_name='jugadorherencia',
            name='tipo',
            field=models.CharField(choices=[('CASTIGADO', 'Castigado (expulsado del equipo)'), ('VITALICIO', 'Expulsado de por vida'), ('ASCENSO', 'Ascendido (desde otra categoría)'), ('DESCENSO', 'Descendido (desde otra categoría)'), ('DESAPARECE', 'Equipo se dio de baja')], max_length=12),
        ),
    ]
