# Generated by Django 6.0.6 on 2026-09-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0085_suspensionjugador_vitalicia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporada',
            name='puntos_default',
            field=models.IntegerField(default=3, help_text='Puntos que se restan al equipo que pierde un partido por default (mora, abandono o alineación indebida). Ej. 3 = -3 puntos en la tabla por cada partido perdido por default.', verbose_name='Puntos que pierde por derrota default'),
        ),
    ]