# Generated by Django 6.0.5 on 2026-09-12 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0087_visita'),
    ]

    operations = [
        migrations.AddField(
            model_name='visita',
            name='inicio',
            field=models.BooleanField(default=False, help_text='True si esta página abre una nueva visita (sin otra actividad del mismo visitante en la última hora).', verbose_name='Inicio de visita'),
        ),
    ]
