# Generated by Django 6.0.5 on 2026-09-12 03:05

import datetime

from django.db import migrations


def backfill_inicio(apps, schema_editor):
    """Marca como inicio de visita las primeras páginas de cada visitante
    (agrupado por IP, o sesión si no hay IP): la primera actividad y toda
    página cuya actividad previa del mismo visitante tenga más de 1 hora."""
    Visita = apps.get_model("league", "Visita")
    horas = datetime.timedelta(hours=1)
    ultima = {}       # ('ip'|'sesion', valor) -> fecha
    inicios = set()
    for v in Visita.objects.all().order_by("fecha"):
        if v.ip:
            clave = ("ip", v.ip)
        elif v.sesion:
            clave = ("sesion", v.sesion)
        else:
            inicios.add(v.pk)
            continue
        prev = ultima.get(clave)
        if prev is None or (v.fecha - prev) >= horas:
            inicios.add(v.pk)
        ultima[clave] = v.fecha
    if inicios:
        Visita.objects.filter(pk__in=inicios).update(inicio=True)


def reverse_inicio(apps, schema_editor):
    Visita = apps.get_model("league", "Visita")
    Visita.objects.update(inicio=False)


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0088_visita_inicio'),
    ]

    operations = [
        migrations.RunPython(backfill_inicio, reverse_inicio),
    ]