# Generated by Django 6.0.6 on 2026-09-12 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0089_visita_backfill_inicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='jornada',
            name='fecha_original',
            field=models.DateField(blank=True, help_text='Fecha en que estaba programada la jornada ANTES de suspenderla. Se conserva aunque el calendario se recorra, para que el aviso del dashboard se muestre TODO el día que era el programado.', null=True, verbose_name='Día programado original'),
        ),
    ]
