# Generated by Django 6.0.6 on 2026-09-15 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0090_jornada_fecha_original'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descripcion', models.TextField(blank=True, default='', verbose_name='Descripción')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='anuncios/', verbose_name='Imagen')),
                ('enlace', models.URLField(blank=True, default='', verbose_name='Enlace del anunciante')),
                ('tamano', models.CharField(choices=[('PREMIUM', 'Premium (franja grande)'), ('MEDIO', 'Medio (columna)'), ('ECONOMICO', 'Económico (franja fina)')], default='MEDIO', max_length=20, verbose_name='Tamaño')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_inicio', models.DateField(blank=True, null=True, verbose_name='Inicio de vigencia')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fin de vigencia')),
                ('orden', models.IntegerField(default=0, verbose_name='Orden')),
                ('impresiones', models.PositiveIntegerField(default=0, verbose_name='Impresiones')),
                ('clics', models.PositiveIntegerField(default=0, verbose_name='Clics')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Anuncio',
                'verbose_name_plural': 'Anuncios',
                'ordering': ['orden', '-creado'],
            },
        ),
        migrations.CreateModel(
            name='AnuncioClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('sesion', models.CharField(blank=True, default='', max_length=64, verbose_name='Sesión')),
                ('fecha', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha')),
                ('anuncio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_click', to='league.anuncio')),
            ],
            options={
                'verbose_name': 'Clic de anuncio',
                'verbose_name_plural': 'Clics de anuncios',
                'ordering': ['-fecha'],
            },
        ),
    ]
