# Generated by Django 6.0.6 on 2026-09-15 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0091_anuncio_anuncioclick'),
    ]

    operations = [
        migrations.AddField(
            model_name='anuncio',
            name='color_fondo',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Color de fondo (opcional, ej. #2d6b2e)'),
        ),
    ]
