# Generated by Django 6.0.6 on 2026-09-16 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0092_anuncio_color_fondo'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionliga',
            name='rotacion_banners_segundos',
            field=models.PositiveIntegerField(default=30, help_text='Cuántos segundos se muestra cada anuncio en el inicio antes de rotar al siguiente. Mínimo 5.', verbose_name='Segundos de rotación de banners'),
        ),
    ]
