# Generated by Django 6.0.6 on 2026-09-16 04:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0093_configuracionliga_rotacion_banners_segundos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PronosticoQuiniela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goles_local', models.PositiveIntegerField(default=0, verbose_name='Goles local (pronóstico)')),
                ('goles_visitante', models.PositiveIntegerField(default=0, verbose_name='Goles visitante (pronóstico)')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pronosticos_quiniela', to='league.partido', verbose_name='Partido')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pronosticos_quiniela', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Pronóstico de Quiniela',
                'verbose_name_plural': 'Pronósticos de Quiniela',
                'ordering': ['partido__fecha_hora'],
                'unique_together': {('usuario', 'partido')},
            },
        ),
    ]
