# Generated by Django 6.0.6 on 2026-09-17 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0094_pronosticoquiniela'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionliga',
            name='mostrar_quiniela',
            field=models.BooleanField(default=True, help_text='Muestra u oculta el botón QUINIELA en el menú de navegación del sitio.', verbose_name='Mostrar botón de Quiniela'),
        ),
    ]
