# Generated by Django 6.0.6 on 2026-09-17 02:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0095_configuracionliga_mostrar_quiniela'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Descarga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('APK', 'App Android (APK)'), ('REGLAMENTO', 'Reglamento (PDF)')], db_index=True, max_length=20, verbose_name='Archivo')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('user_agent', models.CharField(blank=True, default='', max_length=255, verbose_name='Agente')),
                ('referer', models.CharField(blank=True, default='', max_length=255, verbose_name='Origen')),
                ('sesion', models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='Sesión')),
                ('fecha', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='descargas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Descarga',
                'verbose_name_plural': 'Descargas',
                'ordering': ['-fecha'],
            },
        ),
    ]
