# Generated by Django 6.0.6 on 2026-09-17 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0096_descarga'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionliga',
            name='ips_excluidas',
            field=models.TextField(blank=True, default='', help_text='IPs que NO se cuentan en las métricas del sitio (visitas, impresiones, clics y descargas). Una por línea o separadas por coma. Admite comodín al final (ej. 190.12.34.*). Útil para excluir tu casa u oficina.', verbose_name='IPs excluidas de métricas'),
        ),
    ]
