# Generated by Django 6.0.6 on 2026-09-17 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0097_configuracionliga_ips_excluidas'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnuncioImpresion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(db_index=True, verbose_name='Fecha')),
                ('clave', models.CharField(db_index=True, default='', max_length=64, verbose_name='Clave visitante')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('anuncio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impresiones_unicas', to='league.anuncio')),
            ],
            options={
                'verbose_name': 'Impresión única de anuncio',
                'verbose_name_plural': 'Impresiones únicas de anuncios',
                'ordering': ['-creado'],
                'unique_together': {('anuncio', 'fecha', 'clave')},
            },
        ),
    ]
