# Generated by Django 6.0.6 on 2026-09-17 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0098_anuncioimpresion'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnuncioDia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(db_index=True, verbose_name='Fecha')),
                ('impresiones', models.PositiveIntegerField(default=0, verbose_name='Impresiones')),
                ('clics', models.PositiveIntegerField(default=0, verbose_name='Clics')),
                ('anuncio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dias', to='league.anuncio')),
            ],
            options={
                'verbose_name': 'Métrica diaria de anuncio',
                'verbose_name_plural': 'Métricas diarias de anuncios',
                'ordering': ['-fecha'],
                'unique_together': {('anuncio', 'fecha')},
            },
        ),
    ]
