# Generated by Django 6.0.6 on 2026-06-23 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('league', '0054_devicetoken_categorias_devicetoken_es_invitado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='categoria_preferida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_preferencia', to='league.categoria', verbose_name='Categoría preferida'),
        ),
    ]
